//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownsendPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Timeline { get; set; }
        public string Summary { get; set; }
        public string Languages { get; set; }
        public string Screenshot { get; set; }
        public string Github { get; set; }
    }
}
